import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { AuthProvider } from "@/components/auth/AuthContext";
import Navbar from "@/components/Navbar";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Recent-AI",
  description: "Generated by create next app",
};

/**
 * Application root layout that sets global providers, fonts, and the page shell.
 *
 * Wraps the application with theming and authentication providers, applies the
 * Manrope font and base body styles, renders the Navbar, and places `children`
 * inside a centered, responsive container.
 *
 * @param children - Page content to render inside the layout
 * @returns The root HTML structure for the application containing providers, navigation, and page content
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manrope.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <AuthProvider>
            <div className="mx-auto max-w-[1440px] min-h-screen bg-background border-x border-border shadow-2xl transition-colors duration-500">
              <Navbar />
              {children}
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}