from backend.db.repository.fetch_raw_data import fetch_last_days_posts
from langgraph_bot.insert_bot_data import insert_cleaned_data
from .workflow.description_workflow import g,write_description_graph_png
from .workflow.complete_workflow import mjorgraph
from .workflow.workflow import graph
import time


def run_entire_flow():
    all_posts = []
    for c, post in enumerate(fetch_last_days_posts(), 1):
        print("count", c)
        initial_state = { 
            "slug":"",
            "user_input": "generate the post using the given data in the state  and keep it beginner friendly so freshers and new developers can understand the posts.",  #    given to the orchestrator or supervisor by human.
            "messages": [],  #    for AI conversations.
            "data": post["description"],  #     data:Optional[str]
            "topic": post["title"],  #     yet to be finalize.
            "title": post["title"],  #     title:Optional[str]
            "summary": None,  #     generated by ai
            "description": None,  #     generated by AI
            "arxiv_urls": [],  #    found from arxiv
            "documents": [],  #    docs from arxiv
            "tavily_search_result": None,  #    search result by agent.
            "code": None,  #   generated by agent.
            "name":post['source_name'],     #   yet to be discussed
        }

        try:
            result = mjorgraph.invoke(initial_state)

            # Return clean structured output with only relevant fields
            clean_post = {
                "title": result.get("title") or post.get("title"),
                "summary": result.get("summary"),
                "description": result.get("description"),
                "source": post.get("source_name"),
                "slug":result.get("slug")
            }
            time.sleep(12)
        except Exception as e:
            print(f"Graph/mapping failed for post {post.get('title')}: {e}")
            continue

        all_posts.append(clean_post)
        if c == 2:
            break

    return all_posts


if __name__ == "__main__":
    # # Generate the workflow graph PNG on startup (and ensure output directory exists).
    # graph_path = write_description_graph_png()
    # print(f"Workflow graph written to: {graph_path}")
    write_description_graph_png()
    final_ans = run_entire_flow()

    print(type(final_ans), len(final_ans))

    print("Final Answer:" + "=" * 60 + "\n" + "=" * 60)
    print(final_ans)
    print("Final Answer:" + "=" * 60 + "\n" + "=" * 60)

    output = insert_cleaned_data(final_ans)
    if output.get("failed", 0) > 0:
        print(f"Insertion completed with {output['failed']}/{output['total']} failures")
    else:
        print("Data inserted successfully!! BOOM!!")
