from backend.db.repository.fetch_raw_data import fetch_last_days_posts

from .workflow.description_workflow import g


def run_entire_flow():
    c = 1
    all_posts = []
    for post in fetch_last_days_posts():
        c += 1
        print("count", c)
        initial_state = {
            "user_input": None,  #    given to the orchestrator or supervisor by human.
            "messages": [],  #    for AI conversations.
            "data": post["description"],  #     data:Optional[str]
            "topic": post["title"],  #     yet to be finalize.
            "title": post["title"],  #     title:Optional[str]
            "summary": None,  #     generated by ai
            "description": None,  #     generated by AI
            "arxiv_urls": [],  #    found from arxiv
            "documents": [],  #    docs from arxiv
            "tavily_search_result": None,  #    search result by agent.
            "code": None,  #   generated by agent.
            # "name":post['source_name'],     #   yet to be discussed
        }

        all_posts.append(g.invoke(initial_state))
        if c == 3:
            break

    return all_posts


if __name__ == "__main__":
    fianl_ans = run_entire_flow()
    for x in fianl_ans:
        for i in x:
            print("-" * 60)
            print(x[i])
            print("-" * 60)
